"""init

Revision ID: 05e48d245066
Revises: 
Create Date: 2026-01-08 20:15:39.676410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05e48d245066'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zp_album',
    sa.Column('album_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='相册名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='相册描述'),
    sa.Column('cover', sa.String(length=255), nullable=True, comment='相册封面URL'),
    sa.Column('status', sa.Integer(), nullable=False, comment='相册状态'),
    sa.Column('image_count', sa.Integer(), nullable=False, comment='相册图片数量'),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='相册唯一标识符'),
    sa.Column('privacy', sa.String(length=16), nullable=False, comment='相册隐私设置'),
    sa.Column('access_password', sa.String(length=32), nullable=True, comment='相册访问密码'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='相册排序字段'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('album_id'),
    sa.UniqueConstraint('uid', 'name', name='uq_uid_name'),
    comment='相册表'
    )
    op.create_index('idx_uid_status', 'zp_album', ['uid', 'status'], unique=False)
    op.create_index(op.f('ix_zp_album_album_id'), 'zp_album', ['album_id'], unique=False)
    op.create_index(op.f('ix_zp_album_slug'), 'zp_album', ['slug'], unique=True)
    op.create_index(op.f('ix_zp_album_uid'), 'zp_album', ['uid'], unique=False)
    op.create_table('zp_deletion_queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=True, comment='用户ID'),
    sa.Column('imgid', sa.String(length=16), nullable=False, comment='图片唯一ID'),
    sa.Column('path', sa.String(length=64), nullable=False, comment='图片存储路径'),
    sa.Column('thumb_path', sa.String(length=64), nullable=True, comment='缩略图存储路径'),
    sa.Column('storage_slug', sa.String(length=64), nullable=False, comment='存储策略slug'),
    sa.Column('upload_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='上传时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False, comment='用户角色，user普通用户，admin管理员'),
    sa.Column('ip', sa.String(length=45), nullable=False, comment='上传者IP地址'),
    sa.Column('ua', sa.String(length=256), nullable=False, comment='上传者UA'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zp_deletion_queue_imgid'), 'zp_deletion_queue', ['imgid'], unique=True)
    op.create_index(op.f('ix_zp_deletion_queue_status'), 'zp_deletion_queue', ['status'], unique=False)
    op.create_index(op.f('ix_zp_deletion_queue_uid'), 'zp_deletion_queue', ['uid'], unique=False)
    op.create_table('zp_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=True, comment='用户ID'),
    sa.Column('imgid', sa.String(length=16), nullable=False, comment='图片唯一ID'),
    sa.Column('path', sa.String(length=64), nullable=False, comment='图片存储路径'),
    sa.Column('thumb_path', sa.String(length=64), nullable=True, comment='缩略图存储路径'),
    sa.Column('storage_slug', sa.String(length=64), nullable=False, comment='存储策略slug'),
    sa.Column('upload_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='上传时间'),
    sa.Column('album_id', sa.Integer(), nullable=False, comment='相册ID'),
    sa.Column('mime_type', sa.String(length=32), nullable=False, comment='图片MIME类型'),
    sa.Column('width', sa.Integer(), nullable=False, comment='图片宽度'),
    sa.Column('height', sa.Integer(), nullable=False, comment='图片高度'),
    sa.Column('ext', sa.String(length=16), nullable=False, comment='图片扩展名'),
    sa.Column('size', sa.Integer(), nullable=False, comment='图片大小，存储字节'),
    sa.Column('filename', sa.String(length=255), nullable=False, comment='图片原始文件名'),
    sa.Column('is_nsfw', sa.Integer(), nullable=False, comment='是否NSFW色情图片'),
    sa.Column('is_qrcode', sa.Integer(), nullable=False, comment='是否二维码图片'),
    sa.Column('upload_ip', sa.String(length=45), nullable=False, comment='上传者IP地址'),
    sa.Column('hash', sa.String(length=16), nullable=False, comment='图片hash值'),
    sa.PrimaryKeyConstraint('id'),
    comment='图片表'
    )
    op.create_index('idx_uid_album_id', 'zp_image', ['uid', 'album_id'], unique=False)
    op.create_index('idx_uid_hash', 'zp_image', ['uid', 'hash'], unique=False)
    op.create_index(op.f('ix_zp_image_hash'), 'zp_image', ['hash'], unique=False)
    op.create_index(op.f('ix_zp_image_imgid'), 'zp_image', ['imgid'], unique=True)
    op.create_index(op.f('ix_zp_image_uid'), 'zp_image', ['uid'], unique=False)
    op.create_table('zp_metainfo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('imgid', sa.String(length=16), nullable=False, comment='图片唯一ID'),
    sa.Column('token', sa.String(length=32), nullable=True, comment='图片删除token'),
    sa.Column('upload_ua', sa.String(length=256), nullable=False, comment='上传者UA'),
    sa.Column('compressed', sa.Boolean(), nullable=False, comment='是否压缩'),
    sa.Column('views', sa.Integer(), nullable=False, comment='图片浏览量'),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='图片关键词'),
    sa.Column('description', sa.String(length=256), nullable=True, comment='图片描述'),
    sa.Column('exif', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='图片EXIF信息'),
    sa.PrimaryKeyConstraint('id'),
    comment='图片元信息表'
    )
    op.create_index(op.f('ix_zp_metainfo_imgid'), 'zp_metainfo', ['imgid'], unique=True)
    op.create_index(op.f('ix_zp_metainfo_token'), 'zp_metainfo', ['token'], unique=True)
    op.create_table('zp_order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False, comment='商户订单ID'),
    sa.Column('plan_id', sa.Integer(), nullable=True, comment='套餐ID'),
    sa.Column('service_order_id', sa.String(length=64), nullable=True, comment='服务方订单ID'),
    sa.Column('uid', sa.String(length=32), nullable=False, comment='用户唯一UID'),
    sa.Column('currency', sa.String(length=3), nullable=False, comment='货币类型'),
    sa.Column('payment_method', sa.String(length=32), nullable=False, comment='支付方式'),
    sa.Column('order_name', sa.String(length=255), nullable=False, comment='订单名称'),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False, comment='订单金额'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True, comment='支付时间'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='订单状态'),
    sa.Column('ip', sa.String(length=45), nullable=False, comment='注册IP地址'),
    sa.Column('user_agent', sa.String(length=256), nullable=False, comment='注册时的UA'),
    sa.Column('plan_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='下单时套餐快照'),
    sa.Column('remark', sa.Text(), nullable=True, comment='订单备注'),
    sa.PrimaryKeyConstraint('id'),
    comment='订单表'
    )
    op.create_index(op.f('ix_zp_order_order_id'), 'zp_order', ['order_id'], unique=True)
    op.create_index(op.f('ix_zp_order_service_order_id'), 'zp_order', ['service_order_id'], unique=False)
    op.create_index(op.f('ix_zp_order_uid'), 'zp_order', ['uid'], unique=False)
    op.create_table('zp_plan',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False, comment='订阅等级：free/trial/paid'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='订阅名称'),
    sa.Column('daily_limit', sa.Integer(), nullable=False, comment='每日上传限制'),
    sa.Column('monthly_limit', sa.Integer(), nullable=False, comment='每月上传限制'),
    sa.Column('size_limit_mb', sa.Integer(), nullable=False, comment='单文件上传大小限制，MB'),
    sa.Column('storage_limit_mb', sa.Integer(), nullable=False, comment='总存储容量限制，MB'),
    sa.Column('price', sa.Numeric(precision=6, scale=2), nullable=False, comment='价格，单位分'),
    sa.Column('original_price', sa.Numeric(precision=6, scale=2), nullable=False, comment='原价，单位分'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('storage_slug', sa.String(length=64), nullable=False, comment='存储策略slug'),
    sa.Column('description', sa.Text(), nullable=True, comment='套餐描述'),
    sa.Column('valid_days', sa.Integer(), nullable=False, comment='有效期天数'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序字段，越小越靠前'),
    sa.Column('status', sa.Integer(), nullable=False, comment='状态，1启用，0禁用'),
    sa.PrimaryKeyConstraint('id'),
    comment='套餐计划表'
    )
    op.create_table('zp_storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='存储键'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='存储名称'),
    sa.Column('bucket', sa.String(length=128), nullable=True, comment='存储桶名称'),
    sa.Column('endpoint', sa.String(length=256), nullable=True, comment='存储服务地址'),
    sa.Column('access_key', sa.String(length=512), nullable=True, comment='访问密钥'),
    sa.Column('secret_key', sa.String(length=512), nullable=True, comment='密钥'),
    sa.Column('region', sa.String(length=64), nullable=True, comment='存储区域'),
    sa.Column('storage_type', sa.String(length=32), nullable=False, comment='存储类型，如s3、minio等'),
    sa.Column('domain', sa.String(length=256), nullable=False, comment='存储访问域名'),
    sa.Column('extra_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='额外访问域名列表'),
    sa.Column('is_default', sa.Integer(), nullable=False, comment='是否默认存储，0否，1是'),
    sa.Column('status', sa.Integer(), nullable=False, comment='存储状态，0禁用，1启用'),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展参数，保留用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注信息'),
    sa.CheckConstraint('status IN (0, 1)', name='check_status'),
    sa.PrimaryKeyConstraint('id'),
    comment='存储配置表'
    )
    op.create_index(op.f('ix_zp_storage_slug'), 'zp_storage', ['slug'], unique=True)
    op.create_table('zp_subscription',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='订阅名称'),
    sa.Column('tier', sa.String(length=32), nullable=False, comment='订阅等级：free/trial/paid'),
    sa.Column('daily_limit', sa.Integer(), nullable=False, comment='每日上传限制'),
    sa.Column('monthly_limit', sa.Integer(), nullable=False, comment='每月上传限制'),
    sa.Column('size_limit_mb', sa.Integer(), nullable=False, comment='单文件上传大小限制，MB'),
    sa.Column('storage_limit_mb', sa.Integer(), nullable=False, comment='总存储容量限制，MB'),
    sa.Column('order_id', sa.String(length=32), nullable=True, comment='关联订单ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('start_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='开始时间'),
    sa.Column('storage_slug', sa.String(length=64), nullable=True, comment='存储策略slug'),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False, comment='结束时间'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注信息'),
    sa.PrimaryKeyConstraint('id'),
    comment='订阅表'
    )
    op.create_index(op.f('ix_zp_subscription_uid'), 'zp_subscription', ['uid'], unique=False)
    op.create_table('zp_sys_option',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False, comment='选项键'),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='选项值'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='系统配置表'
    )
    op.create_index(op.f('ix_zp_sys_option_key'), 'zp_sys_option', ['key'], unique=True)
    op.create_table('zp_user',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('uid', sa.String(length=32), nullable=False, comment='用户唯一UID'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='用户昵称，保留用'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='用户邮箱，唯一'),
    sa.Column('password', sa.String(length=32), nullable=True, comment='用户密码，MD5加密存储'),
    sa.Column('reg_ip', sa.String(length=45), nullable=False, comment='注册IP地址'),
    sa.Column('reg_ua', sa.String(length=256), nullable=False, comment='注册时的UA'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('status', sa.Integer(), nullable=False, comment='用户状态，0禁用，1启用'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='用户角色，user普通用户，admin管理员'),
    sa.Column('avatar', sa.String(length=255), nullable=True, comment='用户头像URL'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注信息'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户表'
    )
    op.create_index(op.f('ix_zp_user_email'), 'zp_user', ['email'], unique=True)
    op.create_index(op.f('ix_zp_user_id'), 'zp_user', ['id'], unique=False)
    op.create_index(op.f('ix_zp_user_uid'), 'zp_user', ['uid'], unique=True)
    op.create_table('zp_user_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False, comment='用户唯一UID'),
    sa.Column('compress', sa.Boolean(), nullable=False, comment='是否启用图片压缩'),
    sa.Column('watermark_enabled', sa.Boolean(), nullable=False, comment='是否启用水印'),
    sa.Column('watermark_text', sa.String(length=20), nullable=True, comment='水印文字'),
    sa.Column('upload_count', sa.BigInteger(), nullable=False, comment='用户上传总量'),
    sa.Column('storage_bytes', sa.BigInteger(), nullable=False, comment='用户存储总字节数'),
    sa.Column('storage_domains', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='用户默认存储域名'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('ext', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='扩展参数，保留用'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户配置表'
    )
    op.create_index(op.f('ix_zp_user_config_uid'), 'zp_user_config', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zp_user_config_uid'), table_name='zp_user_config')
    op.drop_table('zp_user_config')
    op.drop_index(op.f('ix_zp_user_uid'), table_name='zp_user')
    op.drop_index(op.f('ix_zp_user_id'), table_name='zp_user')
    op.drop_index(op.f('ix_zp_user_email'), table_name='zp_user')
    op.drop_table('zp_user')
    op.drop_index(op.f('ix_zp_sys_option_key'), table_name='zp_sys_option')
    op.drop_table('zp_sys_option')
    op.drop_index(op.f('ix_zp_subscription_uid'), table_name='zp_subscription')
    op.drop_table('zp_subscription')
    op.drop_index(op.f('ix_zp_storage_slug'), table_name='zp_storage')
    op.drop_table('zp_storage')
    op.drop_table('zp_plan')
    op.drop_index(op.f('ix_zp_order_uid'), table_name='zp_order')
    op.drop_index(op.f('ix_zp_order_service_order_id'), table_name='zp_order')
    op.drop_index(op.f('ix_zp_order_order_id'), table_name='zp_order')
    op.drop_table('zp_order')
    op.drop_index(op.f('ix_zp_metainfo_token'), table_name='zp_metainfo')
    op.drop_index(op.f('ix_zp_metainfo_imgid'), table_name='zp_metainfo')
    op.drop_table('zp_metainfo')
    op.drop_index(op.f('ix_zp_image_uid'), table_name='zp_image')
    op.drop_index(op.f('ix_zp_image_imgid'), table_name='zp_image')
    op.drop_index(op.f('ix_zp_image_hash'), table_name='zp_image')
    op.drop_index('idx_uid_hash', table_name='zp_image')
    op.drop_index('idx_uid_album_id', table_name='zp_image')
    op.drop_table('zp_image')
    op.drop_index(op.f('ix_zp_deletion_queue_uid'), table_name='zp_deletion_queue')
    op.drop_index(op.f('ix_zp_deletion_queue_status'), table_name='zp_deletion_queue')
    op.drop_index(op.f('ix_zp_deletion_queue_imgid'), table_name='zp_deletion_queue')
    op.drop_table('zp_deletion_queue')
    op.drop_index(op.f('ix_zp_album_uid'), table_name='zp_album')
    op.drop_index(op.f('ix_zp_album_slug'), table_name='zp_album')
    op.drop_index(op.f('ix_zp_album_album_id'), table_name='zp_album')
    op.drop_index('idx_uid_status', table_name='zp_album')
    op.drop_table('zp_album')
    # ### end Alembic commands ###
