"""op sub index

Revision ID: 0c096ba0e423
Revises: 1ad2b634ebc3
Create Date: 2026-01-21 20:56:04.982572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c096ba0e423'
down_revision: Union[str, Sequence[str], None] = '1ad2b634ebc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zp_subscription', sa.Column('status', sa.String(length=16), server_default='active', nullable=False, comment='订阅状态'))
    op.create_index('idx_sub_uid_status_end_at', 'zp_subscription', ['uid', 'status', 'end_at'], unique=False)
    op.add_column('zp_token', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True, comment='最近使用时间'))
    op.create_index('idx_token_status_lastused', 'zp_token', ['status', 'last_used_at'], unique=False)
    op.alter_column('zp_user_config', 'storage_bytes',
               existing_type=sa.BIGINT(),
               server_default=sa.text('0'),
               existing_comment='用户存储总字节数',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zp_user_config', 'storage_bytes',
               existing_type=sa.BIGINT(),
               server_default=None,
               existing_comment='用户存储总字节数',
               existing_nullable=False)
    op.drop_index('idx_token_status_lastused', table_name='zp_token')
    op.drop_column('zp_token', 'last_used_at')
    op.drop_index('idx_sub_uid_status_end_at', table_name='zp_subscription')
    op.drop_column('zp_subscription', 'status')
    # ### end Alembic commands ###
