"""op tables

Revision ID: 1ad2b634ebc3
Revises: 4c7faba20317
Create Date: 2026-01-21 12:35:59.415782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad2b634ebc3'
down_revision: Union[str, Sequence[str], None] = '4c7faba20317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_nsfw_porn', 'zp_image', ['upload_at'], unique=False, postgresql_where=sa.text('is_nsfw = 3'))
    op.create_index('idx_qrcode_true', 'zp_image', ['upload_at'], unique=False, postgresql_where=sa.text('is_qrcode = 3'))
    op.create_index('idx_uid_is_nsfw', 'zp_image', ['uid', 'is_nsfw'], unique=False)
    op.create_index('idx_uid_is_qrcode', 'zp_image', ['uid', 'is_qrcode'], unique=False)
    op.create_index('idx_uid_upload_at', 'zp_image', ['uid', 'upload_at'], unique=False)
    op.create_index(op.f('ix_zp_image_upload_at'), 'zp_image', ['upload_at'], unique=False)
    op.alter_column('zp_user', 'status',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_comment='用户状态，0禁用，1启用',
               existing_nullable=False)
    op.alter_column('zp_user', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'user'"),
               existing_comment='用户角色，user普通用户，admin管理员',
               existing_nullable=False)
    op.alter_column('zp_user_config', 'compress',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_comment='是否启用图片压缩',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zp_user_config', 'compress',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_comment='是否启用图片压缩',
               existing_nullable=False)
    op.alter_column('zp_user', 'role',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_comment='用户角色，user普通用户，admin管理员',
               existing_nullable=False)
    op.alter_column('zp_user', 'status',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_comment='用户状态，0禁用，1启用',
               existing_nullable=False)
    op.drop_index(op.f('ix_zp_image_upload_at'), table_name='zp_image')
    op.drop_index('idx_uid_upload_at', table_name='zp_image')
    op.drop_index('idx_uid_is_qrcode', table_name='zp_image')
    op.drop_index('idx_uid_is_nsfw', table_name='zp_image')
    op.drop_index('idx_qrcode_true', table_name='zp_image', postgresql_where=sa.text('is_qrcode = 3'))
    op.drop_index('idx_nsfw_porn', table_name='zp_image', postgresql_where=sa.text('is_nsfw = 3'))
    # ### end Alembic commands ###
