"""add page table

Revision ID: 1c1976869702
Revises: cae71a649468
Create Date: 2026-01-13 10:53:35.932270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c1976869702'
down_revision: Union[str, Sequence[str], None] = 'cae71a649468'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zp_page',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='页面别名'),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False, comment='页面状态'),
    sa.PrimaryKeyConstraint('id'),
    comment='页面表'
    )
    op.create_index(op.f('ix_zp_page_slug'), 'zp_page', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zp_page_slug'), table_name='zp_page')
    op.drop_table('zp_page')
    # ### end Alembic commands ###
