"""add user_config column

Revision ID: 2db37fd6eda3
Revises: aa5bfae75323
Create Date: 2026-01-23 09:23:38.814296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db37fd6eda3'
down_revision: Union[str, Sequence[str], None] = 'aa5bfae75323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zp_user_config', sa.Column('nsfw_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='色情图片数量'))
    op.add_column('zp_user_config', sa.Column('qrcode_count', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='二维码图片数量'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zp_user_config', 'qrcode_count')
    op.drop_column('zp_user_config', 'nsfw_count')
    # ### end Alembic commands ###
