"""add token table

Revision ID: 4c7faba20317
Revises: 1c1976869702
Create Date: 2026-01-19 10:41:21.836010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7faba20317'
down_revision: Union[str, Sequence[str], None] = '1c1976869702'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zp_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('uid', sa.String(length=32), nullable=False, comment='用户ID'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='Token名称'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='过期时间（NULL=永不过期）'),
    sa.Column('token_type', sa.String(length=32), nullable=False, comment='Token类型'),
    sa.Column('token', sa.String(length=128), nullable=False, comment='Token值'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='Token状态'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.PrimaryKeyConstraint('id'),
    comment='API Tokens表'
    )
    op.create_index('idx_token_uid_status', 'zp_token', ['uid', 'status'], unique=False)
    op.create_index(op.f('ix_zp_token_token'), 'zp_token', ['token'], unique=True)
    op.create_index(op.f('ix_zp_token_uid'), 'zp_token', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zp_token_uid'), table_name='zp_token')
    op.drop_index(op.f('ix_zp_token_token'), table_name='zp_token')
    op.drop_index('idx_token_uid_status', table_name='zp_token')
    op.drop_table('zp_token')
    # ### end Alembic commands ###
