"""add delete size

Revision ID: aa5bfae75323
Revises: 0c096ba0e423
Create Date: 2026-01-22 10:48:50.178112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa5bfae75323'
down_revision: Union[str, Sequence[str], None] = '0c096ba0e423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zp_deletion_queue', sa.Column('size', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='图片大小，存储字节'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zp_deletion_queue', 'size')
    # ### end Alembic commands ###
