"""add redeem_code

Revision ID: c1396461755e
Revises: 2db37fd6eda3
Create Date: 2026-03-02 16:08:25.073557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1396461755e'
down_revision: Union[str, Sequence[str], None] = '2db37fd6eda3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zp_redeem_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=True, comment='用户UID'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='用户邮箱'),
    sa.Column('use_ip', sa.String(length=45), nullable=True, comment='IP地址'),
    sa.Column('use_ua', sa.String(length=256), nullable=True, comment='UA'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='失效时间'),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True, comment='使用时间'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注信息'),
    sa.CheckConstraint("status IN ('unused', 'used', 'expired', 'disabled')", name='check_redeem_code_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zp_redeem_code_code'), 'zp_redeem_code', ['code'], unique=True)
    op.create_index(op.f('ix_zp_redeem_code_email'), 'zp_redeem_code', ['email'], unique=False)
    op.create_index(op.f('ix_zp_redeem_code_uid'), 'zp_redeem_code', ['uid'], unique=False)
    op.create_index('idx_nsfw_id_desc', 'zp_image', ['is_nsfw', 'id'], unique=False, postgresql_ops={'id': 'desc'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_nsfw_id_desc', table_name='zp_image', postgresql_ops={'id': 'desc'})
    op.drop_index(op.f('ix_zp_redeem_code_uid'), table_name='zp_redeem_code')
    op.drop_index(op.f('ix_zp_redeem_code_email'), table_name='zp_redeem_code')
    op.drop_index(op.f('ix_zp_redeem_code_code'), table_name='zp_redeem_code')
    op.drop_table('zp_redeem_code')
    # ### end Alembic commands ###
