"""add login log

Revision ID: cae71a649468
Revises: 05e48d245066
Create Date: 2026-01-13 09:54:19.981890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae71a649468'
down_revision: Union[str, Sequence[str], None] = '05e48d245066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zp_login_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False, comment='用户ID'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='用户邮箱'),
    sa.Column('login_ip', sa.String(length=45), nullable=False, comment='登录IP地址'),
    sa.Column('login_ua', sa.String(length=256), nullable=False, comment='登录时的UA'),
    sa.Column('login_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='登录时间'),
    sa.Column('token', sa.String(length=64), nullable=False, comment='登录token'),
    sa.Column('status', sa.Integer(), nullable=False, comment='登录状态，1成功，0失败'),
    sa.Column('login_location', sa.String(length=100), nullable=True, comment='登录位置'),
    sa.Column('fail_reason', sa.String(length=100), nullable=True, comment='登录失败原因'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    comment='用户日志表'
    )
    op.create_index('idx_uid_login_at', 'zp_login_log', ['uid', 'login_at'], unique=False)
    op.create_index(op.f('ix_zp_login_log_email'), 'zp_login_log', ['email'], unique=False)
    op.create_index(op.f('ix_zp_login_log_uid'), 'zp_login_log', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zp_login_log_uid'), table_name='zp_login_log')
    op.drop_index(op.f('ix_zp_login_log_email'), table_name='zp_login_log')
    op.drop_index('idx_uid_login_at', table_name='zp_login_log')
    op.drop_table('zp_login_log')
    # ### end Alembic commands ###
